[build]
  command = "npm install --force && npm run build"
  publish = "build"
  
[context.branch-deploy]
  command = "npm install && npm run build"
  publish = "build"  # Change this to your build output directory

[context.deploy-preview]
  command = "npm install && npm run build"
  publish = "build"  # Change this to your build output directory

[build.environment]
  NODE_VERSION = "18"  # Change this to your desired Node.js version

